package co.kr.kwon.deliveryapp.model

enum class CellType {

    EMPTY_CELL,
    RESTAURANT_CELL,
    LIKE_RESTAURANT_CELL,
    FOOD_CELL,
    REVIEW_CELL,
    ORDER_FOOD_CELL,
    ORDER_CELL,
    ORDER_HISTORY_LIST_CELL,
    GALLERY_PHOTO,
    MENU_LIST_CELL,
    UNWRITTEN_REVIEW_CELL
}
